import Menu from "@src/components/Menu";
import "./globals.css";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import Image from "next/image";
import Link from "next/link";

const jost = Jost({ subsets: ["latin"], variable: "--font-jost" });

export const metadata: Metadata = {
  title: "PetsPaw",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={`${jost.variable} font-sans`}>
        <div className="p-[30px] flex gap-5 justify-between h-full items-stretch selection:bg-red-light">
          <div className="flex-1 flex flex-col items-center">
            <div>
              <div className="mb-20 max-w-max">
                <Link href="/">
                  <Image
                    src="/logo.svg"
                    width={104}
                    height={24}
                    alt="Company logo"
                  />
                </Link>
              </div>
              <h1 className="mb-2 text-[2.75rem] font-medium">Hi!👋</h1>
              <p className="mb-14 text-xl text-grey">
                Welcome to MacPaw Bootcamp 2023
              </p>
              <div>
                <p className="mb-5 text-xl font-medium">
                  Let&apos;s start using The Cat API
                </p>
                <Menu />
              </div>
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
